### ISSUE TITLE
questions about this lib

### ISSUE THREAD

**Issue by tsabbay** [dys-solutions/crm-sdk#12]
hi guys,
im about to start a nice project with the dynamicscrm platform.
few q about your api:
1- does it support CREATION of an object (insert) ?
2-does it support UPDATES of an object ?
3-upd of sepecific object properties ?
4-upserts (update/insert if not found) ?
5-when can i see some documentaion of the supported objects/fields ?
6-how can i donate to you something ?
thx,
b.

**Comment by nsteenbeek** [comment]
Hi tsabbay,

This lib supports the CRM web api in two ways:

1. [WebAPI](https://github.com/dys-solutions/crm-sdk/blob/develop/WebAPI.md)
2. [Entity abstraction](https://github.com/dys-solutions/crm-sdk/blob/develop/Entity.md)

Looking to your questions 1, 2, 3 and 4 the second way (Entity) is the best way to go. But you can combine both of course.
Ad1) See [Entity.create](https://github.com/dys-solutions/crm-sdk/blob/develop/Entity.md)
Ad2) See [Save](https://github.com/dys-solutions/crm-sdk/blob/develop/Entity.md)
Ad3) Entity attributes defined in the get/query can be upd. See [Save](https://github.com/dys-solutions/crm-sdk/blob/develop/Entity.md)
Ad4) Save will do insert if entity is a new one and update if entity is existing one
Ad5) There is already a lot of documentation. Please let me know which documentation needs to be extended or added. In summary in the [Entity.get or Entity.query](https://github.com/dys-solutions/crm-sdk/blob/develop/Entity.md) you can specify the Entity attributes in the 'select' and modify and save those changes.
Ad6) This library is made by [Dynamics Software](http://www.dynamicssoftware.com/) and is free under [MIT license](https://github.com/dys-solutions/crm-sdk/blob/master/LICENSE). Some features like workflow, batches, etc, are only available in the enterprise version. They are marked in the documentation. 
You can support this lib by starring this lib and spread the good word.

Please let me know any questions and all the best for your project.

Best regards,
Niels
